# Generated by Django 3.2.8 on 2021-10-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='StaffMember',
            new_name='MiembroStaff',
        ),
    ]
