# Generated by Django 3.2.8 on 2021-11-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripción', models.CharField(max_length=100)),
                ('fechaCreada', models.DateTimeField(auto_now_add=True)),
                ('subCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='uploads/lessons/img')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('aprobacion', models.BooleanField(verbose_name='Aprobación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('link', models.CharField(max_length=500)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('path', models.FileField(upload_to='uploads/files', verbose_name='Archivo')),
                ('lipo', models.CharField(choices=[('PDF', 'Archivo PDF'), ('IMG', 'Imagen')], max_length=3, verbose_name='Tipo de archivo')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
    ]
