# Generated by Django 3.2.8 on 2021-11-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leccion',
            new_name='Leccione',
        ),
    ]
