# Generated by Django 3.2.8 on 2021-11-03 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria', verbose_name='Categoria'),
        ),
    ]
