# Generated by Django 3.2.8 on 2021-10-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0002_rename_category_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Description',
            new_name='Descripción',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='DateCreated',
            new_name='FechaCreada',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Name',
            new_name='Nombre',
        ),
    ]
