# Generated by Django 3.2.8 on 2021-11-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0002_rename_leccion_leccione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='subCategoria',
            new_name='categoriaPadre',
        ),
    ]
