# Generated by Django 3.2.8 on 2021-11-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0003_rename_subcategoria_categoria_categoriapadre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leccione',
            new_name='Leccion',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoriaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria', verbose_name='Categoria perteneciente'),
        ),
    ]
