# Generated by Django 3.2.8 on 2021-10-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0004_categoria_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='SubCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.categoria'),
        ),
    ]
